version: '3.7'

services:
   db:
     image: mysql:8.0
     volumes:
       - ./db:/var/lib/mysql
     restart: unless-stopped
     ports:
       - "3306:3306" 
     environment:
       MYSQL_ROOT_PASSWORD: R11J2I8oanPSjER
       MYSQL_DATABASE: wpdefault
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: P7Msjz7hGPECYx1

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - "8282:80"
     environment:
       PMA_HOST: db
       PMA_ARBITRARY: 1
       MYSQL_ROOT_PASSWORD: R11J2I8oanPSjER

   wp:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: unless-stopped
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - ./data:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: P7Msjz7hGPECYx1
       WORDPRESS_DB_NAME: wpdefault


