version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.440.2-lts-jdk17
    container_name: jenkins
    ports:
      - "8006:8080"
    volumes:
      - /home/jenkins/data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/jenkins/temp:/docker_temp
    user: 'root'

volumes:
  jenkins_home:

networks:
  jenkinsnet:

